---
- name: Installation de mariadb
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: true
  become: true
  when: mariadb_version == "latest"

- name: Création de la base de données test
  ansible.builtin.mysql_db:
    name: test
    state: present
  become: true
  when: mariadb_version == "latest"

- name: Création de l'utilisateur test
  ansible.builtin.mysql_user:
    name: test
    password: test
    priv: "test.*:ALL"
    state: present
  become: true
  when: mariadb_version == "latest"
password: 123456
