---
- name: Installation de phpmyadmin
  ansible.builtin.apt:
    name: phpmyadmin
    state: present
    update_cache: true
  become: true
  when: phpmyadmin_version == "latest"

- name: Configuration de phpmyadmin
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/phpmyadmin/files/phpmyadmin.conf.yml.j2
    dest: /etc/apache2/conf-available/phpmyadmin.conf
  become: true
  when: phpmyadmin_version == "latest"

  notify:
    - Redémarrer Apache